"""Typed configuration models and their file-backed persistence boundary."""

from .models import (
    ACCENT_PRESETS,
    DEFAULT_DISPLAY_SOURCES,
    DEFAULT_ICON_NAME,
    DEFAULT_LYRICS_SOURCES,
    LEAD_MS_LIMIT,
    VALID_DISPLAY_SOURCES,
    VALID_LYRICS_SOURCES,
    Config,
    FxIntensity,
    FxTransition,
    InterludeCountdown,
    InterludeStyle,
    LyricsScript,
    PanelStyle,
    PanelWidthMode,
    ThemeMode,
    UiLanguage,
    clamp_port,
)
from .schema import SETTINGS_CONFIG_FIELDS, SETTINGS_PAGE_FIELDS
from .store import (
    APP_DIR_NAME,
    CONFIG_FILE_NAME,
    MAX_CONFIG_BYTES,
    ConfigStore,
    config_dir,
    config_path,
    load_config,
    save_config,
)

__all__ = [
    "ACCENT_PRESETS",
    "APP_DIR_NAME",
    "CONFIG_FILE_NAME",
    "Config",
    "ConfigStore",
    "DEFAULT_DISPLAY_SOURCES",
    "DEFAULT_ICON_NAME",
    "DEFAULT_LYRICS_SOURCES",
    "FxIntensity",
    "FxTransition",
    "InterludeCountdown",
    "InterludeStyle",
    "LEAD_MS_LIMIT",
    "LyricsScript",
    "MAX_CONFIG_BYTES",
    "PanelStyle",
    "PanelWidthMode",
    "SETTINGS_CONFIG_FIELDS",
    "SETTINGS_PAGE_FIELDS",
    "ThemeMode",
    "UiLanguage",
    "VALID_DISPLAY_SOURCES",
    "VALID_LYRICS_SOURCES",
    "clamp_port",
    "config_dir",
    "config_path",
    "load_config",
    "save_config",
]
