"""Localized labels for the manual lyric-search window."""

from typing import Final

SEARCH_STRINGS: Final[dict[str, dict[str, str]]] = {
    "overlay.search_lyrics": {
        "en": "Search lyrics",
        "zh-Hans": "查找歌词",
        "zh-Hant": "查找歌詞",
        "ja": "歌詞を検索",
    },
    "search.title": {
        "en": "Find lyrics",
        "zh-Hans": "查找歌词",
        "zh-Hant": "查找歌詞",
        "ja": "歌詞を検索",
    },
    "search.subtitle": {
        "en": "Search providers and choose the lyric version for this track.",
        "zh-Hans": "搜索不同来源，为当前歌曲选择合适的歌词版本。",
        "zh-Hant": "搜尋不同來源，為目前歌曲選擇合適的歌詞版本。",
        "ja": "複数のソースを検索し、この曲に合う歌詞を選択します。",
    },
    "search.current_lyrics.none": {
        "en": "No lyric document",
        "zh-Hans": "暂无歌词",
        "zh-Hant": "目前沒有歌詞",
        "ja": "歌詞なし",
    },
    "search.status.source": {"en": "Lyric source", "zh-Hans": "歌词来源", "zh-Hant": "歌詞來源", "ja": "歌詞ソース"},
    "search.status.origin": {"en": "Acquisition", "zh-Hans": "获取方式", "zh-Hant": "取得方式", "ja": "取得方法"},
    "search.status.player": {"en": "Playback source", "zh-Hans": "播放来源", "zh-Hant": "播放來源", "ja": "再生ソース"},
    "search.status.cache": {"en": "Cache status", "zh-Hans": "缓存状态", "zh-Hant": "快取狀態", "ja": "キャッシュ状態"},
    "search.origin.network": {"en": "Network", "zh-Hans": "网络查询", "zh-Hant": "網路查詢", "ja": "ネットワーク"},
    "search.origin.cache": {"en": "Cache", "zh-Hans": "缓存", "zh-Hant": "快取", "ja": "キャッシュ"},
    "search.origin.live": {
        "en": "Live provider",
        "zh-Hans": "实时提供方",
        "zh-Hant": "即時提供者",
        "ja": "ライブプロバイダー",
    },
    "search.origin.sidecar": {
        "en": "Sidecar file",
        "zh-Hans": "旁车歌词文件",
        "zh-Hant": "旁車歌詞檔案",
        "ja": "サイドカーファイル",
    },
    "search.origin.embedded": {
        "en": "Embedded lyrics",
        "zh-Hans": "内嵌歌词",
        "zh-Hant": "內嵌歌詞",
        "ja": "埋め込み歌詞",
    },
    "search.origin.adapter": {
        "en": "Player adapter",
        "zh-Hans": "播放器适配器",
        "zh-Hant": "播放器轉接器",
        "ja": "プレーヤーアダプター",
    },
    "search.origin.manual": {"en": "Manual selection", "zh-Hans": "手动选择", "zh-Hant": "手動選擇", "ja": "手動選択"},
    "search.playback.mpris": {"en": "MPRIS", "zh-Hans": "MPRIS", "zh-Hant": "MPRIS", "ja": "MPRIS"},
    "search.playback.cider": {"en": "Cider", "zh-Hans": "Cider", "zh-Hant": "Cider", "ja": "Cider"},
    "search.playback.adapter": {
        "en": "External adapter",
        "zh-Hans": "外部适配器",
        "zh-Hant": "外部轉接器",
        "ja": "外部アダプター",
    },
    "search.cache.none": {
        "en": "Not from cache",
        "zh-Hans": "未使用缓存",
        "zh-Hant": "未使用快取",
        "ja": "キャッシュ未使用",
    },
    "search.cache.from": {"en": "From cache", "zh-Hans": "来自缓存", "zh-Hant": "來自快取", "ja": "キャッシュから"},
    "search.cache.manual": {
        "en": "Saved as manual",
        "zh-Hans": "已保存为手动",
        "zh-Hant": "已儲存為手動",
        "ja": "手動として保存済み",
    },
    "search.query": {
        "en": "Search fields",
        "zh-Hans": "搜索条件",
        "zh-Hant": "搜尋條件",
        "ja": "検索条件",
    },
    "search.query_title": {"en": "Song", "zh-Hans": "歌曲", "zh-Hant": "歌曲", "ja": "曲名"},
    "search.query_artist": {"en": "Artist", "zh-Hans": "艺术家", "zh-Hant": "藝人", "ja": "アーティスト"},
    "search.query_album": {"en": "Album", "zh-Hans": "专辑", "zh-Hant": "專輯", "ja": "アルバム"},
    "search.placeholder.title": {
        "en": "Song title",
        "zh-Hans": "歌曲名称",
        "zh-Hant": "歌曲名稱",
        "ja": "曲名",
    },
    "search.placeholder.artist": {
        "en": "Artist name",
        "zh-Hans": "艺术家名称",
        "zh-Hant": "藝人名稱",
        "ja": "アーティスト名",
    },
    "search.placeholder.album": {
        "en": "Album name",
        "zh-Hans": "专辑名称",
        "zh-Hant": "專輯名稱",
        "ja": "アルバム名",
    },
    "btn.search_lyrics": {"en": "Search", "zh-Hans": "搜索", "zh-Hant": "搜尋", "ja": "検索"},
    "btn.apply_lyrics": {
        "en": "Use selected lyrics",
        "zh-Hans": "应用选中歌词",
        "zh-Hant": "套用選取歌詞",
        "ja": "選択した歌詞を適用",
    },
    "search.loading": {"en": "Searching…", "zh-Hans": "搜索中…", "zh-Hant": "搜尋中…", "ja": "検索中…"},
    "search.results": {
        "en": "{count} results",
        "zh-Hans": "{count} 个结果",
        "zh-Hant": "{count} 個結果",
        "ja": "{count} 件",
    },
    "search.no_results": {
        "en": "No lyrics found",
        "zh-Hans": "没有找到歌词",
        "zh-Hant": "找不到歌詞",
        "ja": "歌詞が見つかりません",
    },
    "search.partial_results": {
        "en": "{count} results (unavailable: {sources})",
        "zh-Hans": "{count} 个结果（不可用来源：{sources}）",
        "zh-Hant": "{count} 個結果（無法使用的來源：{sources}）",
        "ja": "{count} 件（利用不可: {sources}）",
    },
    "search.results_heading": {
        "en": "Search results",
        "zh-Hans": "搜索结果",
        "zh-Hant": "搜尋結果",
        "ja": "検索結果",
    },
    "search.query_heading": {
        "en": "Search lyrics",
        "zh-Hans": "搜索歌词",
        "zh-Hant": "搜尋歌詞",
        "ja": "歌詞を検索",
    },
    "search.error.no_query": {
        "en": "Enter a song or an artist to search for",
        "zh-Hans": "请输入歌曲或艺术家再搜索",
        "zh-Hant": "請輸入歌曲或藝人再搜尋",
        "ja": "曲名かアーティストを入力してください",
    },
    "search.error.not_started": {
        "en": "Lyric search is not ready yet",
        "zh-Hans": "歌词搜索尚未就绪",
        "zh-Hant": "歌詞搜尋尚未就緒",
        "ja": "歌詞検索はまだ利用できません",
    },
    "search.error.failed": {
        "en": "The search could not be completed",
        "zh-Hans": "搜索未能完成",
        "zh-Hant": "搜尋未能完成",
        "ja": "検索を完了できませんでした",
    },
    "search.error.apply_failed": {
        "en": "The selected lyrics could not be applied",
        "zh-Hans": "选中的歌词未能应用",
        "zh-Hant": "選取的歌詞未能套用",
        "ja": "選択した歌詞を適用できませんでした",
    },
    "search.error.result_gone": {
        "en": "The selected lyric result is no longer available",
        "zh-Hans": "选中的搜索结果已不在结果里",
        "zh-Hant": "選取的搜尋結果已不在結果裡",
        "ja": "選択した検索結果はもうありません",
    },
    "search.error.track_gone": {
        "en": "The current track is no longer available",
        "zh-Hans": "当前曲目已不在播放",
        "zh-Hant": "目前曲目已不在播放",
        "ja": "再生中の曲がなくなりました",
    },
    "search.unavailable_prefix": {
        "en": "Unavailable: {sources}",
        "zh-Hans": "不可用：{sources}",
        "zh-Hant": "無法使用：{sources}",
        "ja": "利用不可: {sources}",
    },
    "search.high_matches_only": {
        "en": "High matches only",
        "zh-Hans": "仅显示高匹配",
        "zh-Hant": "只顯示高符合",
        "ja": "一致度が高いものだけ",
    },
    "search.unavailable.unconfigured": {
        "en": "source is not configured",
        "zh-Hans": "来源未配置",
        "zh-Hant": "來源未設定",
        "ja": "ソース未設定",
    },
    "search.unavailable.timeout": {
        "en": "request timed out",
        "zh-Hans": "请求超时",
        "zh-Hant": "請求逾時",
        "ja": "リクエストがタイムアウト",
    },
    "search.unavailable.failed": {
        "en": "request failed",
        "zh-Hans": "请求失败",
        "zh-Hant": "請求失敗",
        "ja": "リクエスト失敗",
    },
    "search.unavailable.invalid": {
        "en": "invalid lyric data",
        "zh-Hans": "歌词数据无效",
        "zh-Hant": "歌詞資料無效",
        "ja": "歌詞データが不正",
    },
    "search.unavailable.qqmusic": {
        "en": "metadata search unavailable; needs an exact song id",
        "zh-Hans": "不支持按元数据搜索，需精确歌曲 ID",
        "zh-Hant": "不支援依中繼資料搜尋，需精確歌曲 ID",
        "ja": "メタデータ検索は非対応、正確な曲 ID が必要",
    },
    "search.unavailable.cider": {
        "en": "only exposes the active player track",
        "zh-Hans": "仅提供当前播放的曲目",
        "zh-Hant": "僅提供目前播放的曲目",
        "ja": "再生中の曲のみ取得可能",
    },
    "search.unavailable_source": {
        "en": "{source}: {reason}",
        "zh-Hans": "{source}：{reason}",
        "zh-Hant": "{source}：{reason}",
        "ja": "{source}: {reason}",
    },
    "search.current_duration_unknown": {"en": "Unknown", "zh-Hans": "未知", "zh-Hant": "未知", "ja": "不明"},
    "search.column.provider": {"en": "Provider", "zh-Hans": "来源", "zh-Hant": "來源", "ja": "ソース"},
    "search.column.title": {"en": "Title", "zh-Hans": "歌曲", "zh-Hant": "歌曲", "ja": "曲名"},
    "search.column.artist": {"en": "Artist", "zh-Hans": "艺术家", "zh-Hant": "藝人", "ja": "アーティスト"},
    "search.column.album": {"en": "Album", "zh-Hans": "专辑", "zh-Hant": "專輯", "ja": "アルバム"},
    "search.column.duration": {"en": "Duration", "zh-Hans": "时长", "zh-Hant": "時長", "ja": "長さ"},
    "search.column.version": {"en": "Version", "zh-Hans": "歌词版本", "zh-Hant": "歌詞版本", "ja": "バージョン"},
    "search.column.match": {"en": "Match", "zh-Hans": "匹配度", "zh-Hant": "符合度", "ja": "一致度"},
    # Short enough to stay visible in a narrow column: a translated sheet is what
    # most readers choose on, and a long suffix was the first thing to elide away.
    "search.version.translation": {
        "en": " · translated",
        "zh-Hans": " · 翻译",
        "zh-Hant": " · 翻譯",
        "ja": " · 翻訳",
    },
    "search.version.line": {
        "en": "Line by line",
        "zh-Hans": "逐行歌词",
        "zh-Hant": "逐行歌詞",
        "ja": "行単位",
    },
    "search.version.word": {
        "en": "Word by word",
        "zh-Hans": "逐字歌词",
        "zh-Hant": "逐字歌詞",
        "ja": "文字単位",
    },
    "search.version.yrc": {"en": "YRC", "zh-Hans": "YRC", "zh-Hant": "YRC", "ja": "YRC"},
    "search.version.lrc": {"en": "LRC", "zh-Hans": "LRC", "zh-Hant": "LRC", "ja": "LRC"},
    "search.version.krc": {"en": "KRC", "zh-Hans": "KRC", "zh-Hant": "KRC", "ja": "KRC"},
    "search.version.lyrics": {"en": "Lyrics", "zh-Hans": "歌词", "zh-Hant": "歌詞", "ja": "歌詞"},
    "search.match.high": {"en": "High", "zh-Hans": "高", "zh-Hant": "高", "ja": "高"},
    "search.match.medium": {"en": "Medium", "zh-Hans": "中", "zh-Hant": "中", "ja": "中"},
    "search.match.none": {"en": "Unmatched", "zh-Hans": "未匹配", "zh-Hant": "未匹配", "ja": "一致なし"},
    "search.apply.created": {
        "en": "Lyrics applied and saved as manual.",
        "zh-Hans": "歌词已应用，并保存为手动。",
        "zh-Hant": "歌詞已套用，並儲存為手動。",
        "ja": "歌詞を適用し、手動として保存しました。",
    },
    "search.apply.updated": {
        "en": "Lyrics updated and saved as manual.",
        "zh-Hans": "歌词已更新，并保存为手动。",
        "zh-Hant": "歌詞已更新，並儲存為手動。",
        "ja": "歌詞を更新し、手動として保存しました。",
    },
    "search.apply.next_track": {
        "en": "It will be used when this track is looked up again.",
        "zh-Hans": "当前播放曲目未保持不变，将在下次查询时使用。",
        "zh-Hant": "目前播放曲目已變更，將在下次查詢時使用。",
        "ja": "現在の曲が変わったため、次回の検索時に使用します。",
    },
}

__all__ = ["SEARCH_STRINGS"]
